### ISSUE TITLE
Create Script to have all pre-requisites installed?

### ISSUE THREAD

**Issue by pkarjala** [Alvalol/Haxeflixel-ShmupRoguelike#1]
It would be great if there was a way to have the pre-requisites for Haxl and such installed by a script included with your repo so that users do not have to go through the manual process of setting it up themselves.

**Comment by Alvalol** [comment]
Fixed in the latest commit. e5e5a3001f351af620d60055e5c2b5f3fbf330b1

**Comment by pkarjala** [comment]
FYI, you can refer to commits using the hash like d08e7f30ea6b65bc479a70ebc6aa5364fd358d2d

**Comment by Alvalol** [comment]
Fixed in a8434af3dcf0553e3707afa113bd9897a94448d3 then :)
Thanks!
