### ISSUE TITLE
Game breaks 

### ISSUE THREAD

**Issue by PXshadow** [Alvalol/Haxeflixel-ShmupRoguelike#2]
Invalid field access : x
Called from flixel.group.FlxTypedSpriteGroup::remove line 287
Called from objects.enemies.EnemyBullet::kill line 81
Called from objects.enemies.EnemyBullet::interact line 67
Called from objects.enemies.EnemyBullet::collisions line 60
Called from objects.enemies.EnemyBullet::update line 36
Called from flixel.group.FlxTypedGroup::update line 138
Called from flixel.group.FlxTypedGroup::update line 138
Called from flixel.group.FlxTypedGroup::update line 138
Called from states.PlayState::update line 123
Called from flixel.FlxState::tryUpdate line 168
Called from flixel.FlxGame::update line 745
Called from flixel.FlxGame::step line 686
Called from flixel.FlxGame::onEnterFrame line 528
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 286
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430
Done(1)

**Comment by Alvalol** [comment]
Is this causing a crash when getting shot by an enemy? I think the latest changes I made to this class broke it.

**Comment by PXshadow** [comment]
Yes it was.

**Comment by Alvalol** [comment]
This should be fixed by now.
