### ISSUE TITLE
Windows Not working with current libraries 

### ISSUE THREAD

**Issue by PXshadow** [Alvalol/Haxeflixel-ShmupRoguelike#3]
D:/haxeToolKit/lib/polygonal-ds/1,4,1/de/polygonal/ds/ArrayUtil.hx:72: characters 10-18 : Could not convert expression to l-value (CppCallInternal)
Build halted with errors.
Done(1)

**Comment by Alvalol** [comment]
Did you install the necessary libraries?

**Comment by PXshadow** [comment]
Yes.

**Comment by PXshadow** [comment]
Beta version is out of date and there for needs to be updated in the dependencies.hxml . I believe that should fix the problem

**Comment by Alvalol** [comment]
Can you tell me the specific version please? I will update accordingly.

**Comment by PXshadow** [comment]
polygonal-ds 2.0.0-beta
